### ISSUE TITLE
Dotnet expects a bin/release/netcoreapp1.1, needs to run the command `dotnet build ...`

### ISSUE THREAD

**Issue by Rubix982** [ThiagoBarradas/dotnet-core-webapi-with-docker-demo#2]
Hello!

Thank you for making this! Really reduced my time from like 50-60 minutes to just 5 minutes. 

There just needs to be a slight change in the `README.md`. 

The issue is with the `DockerFile`, at the root. The file says the following,
```docker
FROM microsoft/dotnet

# Args / Env
ARG repositoryUrl=https://github.com/ThiagoBarradas/DotNetCore.WebApi.Docker.Demo
ARG configuration=Release
ARG distFolder=DotNetCore.WebApi.Docker.Demo/bin/Release/netcoreapp1.1
ARG apiPort=5000
ARG appFile=DotNetCore.WebApi.Docker.Demo.dll

# Change to temp workspace
WORKDIR /temp

# Get code from the repository
RUN git clone ${repositoryUrl} .

# Restore packages and publish app
RUN dotnet restore
RUN dotnet publish -c ${configuration}

# Copy files to /app
RUN mv /temp/${distFolder} /app
 
# Expose port for the Web API traffic
ENV ASPNETCORE_URLS http://+:${apiPort}
EXPOSE ${apiPort}

# Clear temp files
RUN rm -rf /temp 

# Run application
WORKDIR /app
ENV appFile=$appFile
ENTRYPOINT dotnet $appFile
```

In the line, ```ARG distFolder=DotNetCore.WebApi.Docker.Demo/bin/Release/netcoreapp1.1```, the Dockerfile expects a `/bin/Release/netcoreapp1.1`, but to have that, the following command in the `DotNetCore.WebApi.Docker.Demo`, folder. It generates a `/bin/Release` folder as expected

```sh
dotnet build --configuration Release
```

I am currently working with `.NET SDK (5.0.201)`, and so my `dotnet` commands which generate the release for `2.1`, instead of `1.1`, so now my `Docker` command looks like,
```sh
ARG distFolder=DotNetCore.WebApi.Docker.Demo/bin/Release/netcoreapp2.1
```

There thus needs to be an addition of `dotnet build --configuration Release` in the `README.md`.

**Comment by Rubix982** [comment]
Please check out the PR. Thank you!

**Comment by ThiagoBarradas** [comment]
Fixed!!
